Feat/issue #28
Mockin-2024/backend pull request #31
Opened 2024-10-09 13:37 UTC by suy0594

## **PR**

### 작업 내용
- 해외주식 기간별시세 DTO 업데이트
- 해외주식 기간별시세 API 업데이트
---
### 참고 사항

---
### ✏ Git Close

2024-10-09 14:39 UTC, Richter3766 requested changes
DTO 외에 서비스나 컨트롤러 같은 비즈니스 코드에는 주석이 없는 편이 나은 것 같아요.
이 부분은 저도 조금씩 리팩토링할텐데, 
참고하셔서 완성된 코드에 있는 주석들 천천히 지워가면 좋을 거 같습니다.

고생하셨습니다.
윗 부분 저가 체크해드린 부분만 수정부탁드립니당

2024-10-09 14:39 UTC, Richter3766 commented on src/main/kotlin/com/knu/mockin/kisclient/KISBasicClient.kt
> +        println(LogUtil.toJson(requestParameter))
URI 만들어주는 유틸 함수 생성해뒀어요.
trading 부분 kisClient 보셔서 리팩토링 진행하면 좋을 거 같습니다.
그리고 println과 같은 체크 함수는 PR 단계에선 빼주세요!

2024-10-10 02:54 UTC, suy0594 commented on src/main/kotlin/com/knu/mockin/kisclient/KISBasicClient.kt
> +        println(LogUtil.toJson(requestParameter))
네 알겠습니다!

2024-10-10 04:31 UTC, Richter3766 approved these changes
좋아요~~!

2024-10-10 04:32 UTC, merged